package com.stefanini.model;
// Generated 07/11/2016 12:04:56 by Hibernate Tools 4.3.1.Final

import javax.persistence.GenerationType;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name = "modelo", catalog = "hackathon")
public class Modelo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idModelo", unique = true, nullable = false)
	private Integer idModelo;
	@OneToOne
	@JoinColumn(name="idCategoria", nullable = false)
	private Categoria categoria;
	@Column(name="descricao",length=50)
	private String descricao;

	public Modelo() {
	}
	
	public Modelo(Integer idModelo, Categoria categoria, String descricao) {
		this.idModelo = idModelo;
		this.categoria = categoria;
		this.descricao = descricao;
	}

	public Modelo(Categoria categoria) {
		this.categoria = categoria;
	}

	public Modelo(Categoria categoria, String descricao) {
		this.categoria = categoria;
		this.descricao = descricao;
	}
	
	public Integer getIdModelo() {
		return this.idModelo;
	}

	public void setIdModelo(Integer idModelo) {
		this.idModelo = idModelo;
	}

	public Categoria getCategoria() {
		return categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public String getDescricaoModelo() {
		return this.descricao;
	}
	
	public void setDescricaoModelo(String descricao) {
		this.descricao = descricao;
	}
}
