package com.stefanini.model;
// Generated 07/11/2016 12:04:56 by Hibernate Tools 4.3.1.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Telefones generated by hbm2java
 */
@Entity
@Table(name = "telefones", catalog = "hackathon")
public class Telefones implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="idTelefone", unique=true, nullable=false)
	private Integer id;
	@OneToOne
	@JoinColumn(name = "idTipoTelefone", nullable = false)
	private Tipotelefone tipoTelefone;
	@Column(name="numero",nullable=false,unique=true)
	private int numero;
	private int ddd;
	@ManyToOne(cascade = CascadeType.MERGE)
	@JoinColumn(name ="idProprietario")
	private Proprietario proprietario;
	
	public Telefones() {
	}

	public Telefones(Integer id, Tipotelefone tipoTelefone, int numero, int ddd, Proprietario proprietario) {
		this.id = id;
		this.tipoTelefone = tipoTelefone;
		this.numero = numero;
		this.ddd = ddd;
		this.proprietario = proprietario;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Tipotelefone getTipoTelefone() {
		return tipoTelefone;
	}

	public void setTipoTelefone(Tipotelefone tipoTelefone) {
		this.tipoTelefone = tipoTelefone;
	}

	public int getNumero() {
		return numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	public int getDdd() {
		return ddd;
	}

	public void setDdd(int ddd) {
		this.ddd = ddd;
	}

	public Proprietario getProprietario() {
		return proprietario;
	}

	public void setProprietario(Proprietario proprietario) {
		this.proprietario = proprietario;
	}
}
