package com.stefanini.model;
// Generated 07/11/2016 12:04:56 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
/**
 * Veiculos generated by hbm2java
 */
@Entity
@Table(name = "veiculos", catalog = "hackathon")
public class Veiculos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "placa", unique = true, nullable = false, length = 7)
	private String placa;
	@OneToOne
	@JoinColumn(name="cpfProprietario",nullable=false)
	private Proprietario proprietario;
	@OneToOne
	@JoinColumn(name="idModelo",nullable=false)
	private Modelo modelo;
	@Column(name = "uf", nullable = false, length = 2)
	private String uf;

	public Veiculos() {
	}

	public Veiculos(String placa, Proprietario proprietario, Modelo modelo, String uf) {
		this.placa = placa;
		this.proprietario = proprietario;
		this.modelo = modelo;
		this.uf = uf;
	}

	public String getPlaca() {
		return this.placa;
	}

	public void setPlaca(String placa) {
		this.placa = placa;
	}

	public Proprietario getProprietario() {
		return proprietario;
	}

	public void setProprietario(Proprietario proprietario) {
		this.proprietario = proprietario;
	}

	public Modelo getModelo() {
		return modelo;
	}

	public void setModelo(Modelo modelo) {
		this.modelo = modelo;
	}

	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}
}
